name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: saymore/package-lock.json

      - name: Install dependencies
        working-directory: saymore
        run: npm ci

      - name: Build the Next.js static site
        working-directory: saymore
        run: npm run build  # Static export using output: 'export'

      - name: Verify output folder
        run: ls -R saymore/out  # Debugging step to confirm static files are generated

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: saymore/out  # Deploying the correct folder

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
